image: gitpod/workspace-full-vnc
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
tasks:
  - before: pyenv install 3.10.12; pyenv global 3.10.12
    init: pip3 install -r requirements.txt
    command: python3 pacman.py
